---
- name: Testing Jinja file for output generation
  hosts: all
  tasks:
    - name: First test
      shell: hostname
      register: hnme

    - name: Export output file
      template:
        src: sample.yml
        dest: ~/Ansible/output.csv

