---
- name: Testing Jinja file for output generation
  hosts: all
  tasks:
    - name: First test
      shell: hostname
      register: hostname

    - name: Current_Date
      set_fact:
        current_date: "{{ ansible_date_time.date }}"

    - name: Current_time
      set_fact:
        current_time: "{{ ansible_date_time.time }}"

    - name: Export output file
      template:
        src: sample.j2
       # dest: ~/output_{{ current_date }}_{{ current_time }}.csv
        dest: ~/output_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.csv
