---
- name: Patching Playbook
  hosts: all
  vars_prompt:
    - name: avail
      prompt: Enter package name
      private: no

    - name: install
      prompt: Installation needed?? (yes/no)
      private: no


  tasks:
    - name: Fetching available packages
      yum:
        list: updates
      register: check

    - name: Fetched update
      debug:
        var: check.results

    - name: check {{ avail }} packages
      shell: "yum search {{ avail }}"
      register: package

    - name: package info
      debug:
        var: package.stdout_lines

    - name: Counting
      set_fact:
        count: "{{ package.stdout_lines | length }}"

    - name: Total count
      debug:
        msg : "Total number of packages: '{{ count }}'"

    - shell: echo {{ install }}
      register: install

    - name: Installation
      yum:
        name: "{{ avail }}"
        state: present
      when: {{ install.stdout }} == yes