---
- name: Patching Playbook
  hosts: all
  vars_prompt:
    - name: avail
      prompt: Enter package name
      private: no

  tasks:
    - name: check available packages
      yum:
        list: updates
      register: check

    - debug:
        var: check.results

    - name: check {{ avail }} packages
      yum:
        list: available
      register: available

    - debug:
        msg:  {{ avail }} is {{ 'present' if {{ avail }} in available.stdout else 'Not Available' }}