---
- name: Patching Playbook
  hosts: all
  vars_prompt:
    - name: avail
      prompt: Enter package name
      private: no

  tasks:
    - name: Fetch available packages
      yum:
        list: updates
      register: check

    - debug:
        var: check.results

    - name: check {{ avail }} packages
      yum:
        list: available
      register: available

    - name:
      set_fact:
        package_count: "{{ available.results | length }}"
    - debug:
        var: "{{ package_count }}"
        #msg:  "package is {{ 'present' if 'nginx' in available.stdout else 'Not Available' }}"