---
- name: Patching Playbook
  hosts: all
  vars_prompt:
    - name: avail
      prompt: Enter package name
      private: no

  tasks:
    - name: check available packages
      yum:
        list: updates
      register: check

    - debug:
        var: check.results

    - name: check {{ avail }} packages
      yum:
        list: available
      register: available

    - debug:
        var: available.name
        #msg:  "package is {{ 'present' if 'nginx' in available.stdout else 'Not Available' }}"