---
- name: User, file, Group
  hosts: all
  vars_prompt:
    - name: u1
      prompt: Enter the first user name
      prompt: Enter the first user
      private: no

  tasks:
    - name: User creation
      user:
        name: "{{ item }}"
        password: "1234"
        comment: Test
      with_items:
        - user1
        - user2
        - user3
      register: out

    - name: output
      debug:
        var: out