---
- name: User, file, Group
  hosts: all
  tasks:
    - name: User creation
      user:
        name: "{{ item }}"
        with_items:
          - user1
          - user2
          - user3
        password: "1234"
        comment: Test
        register: out


    - name: output
      debug:
        var: out