---
- name: Patching on ubuntu/Debian
  hosts: all
  tasks:

    - name: Check for update
      apt:
        update_cache: yes
    - shell: apt list --upgradable | wc -l
      register: count

    - name: Show available updates
      debug:
        var: count.stdout_lines

    - name: Installing the patches
      apt:
        upgrade: dist
        cache_valid_time: 15
    - debug:
        msg: Patching completed, pls reboot the serve

