---
- name: Patching on ubuntu/Debian
  hosts: all
  tasks:

    - name: Check for update
      apt:
        update_cache: yes
        upgrade: dist
      register: count

    - name: Show available updates
      debug:
        var: count.stdout_lines

