---
- name: Web application deployment
  hosts: all
  become: true
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: present

    - name: Install required package
      yum: name={{ item }} state=present
      with_items:
        - wget
        - zip
        - httpd

