---
- name: Web application deployment
  hosts: all
  become: true
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install required package
      yum: name={{ item }} state=present
      with_items:
        - wget
        - zip
        - httpd

    - name: download source files
      wget:
        src: https://www.free-css.com/assets/files/free-css-templates/download/page296/healet.zip
        dest: /tmp
        mode: 777

