---
- name: Web application deployment
  hosts: all
  become: true
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest

    - name: Install required package
      yum: name={{ item }} state=present
      with_items:
        - wget
        - zip
        - httpd

    - name: download source files
      get_url:
        url: "https://www.free-css.com/assets/files/free-css-templates/download/page296/healet.zip"
        dest: /tmp

    - name: copy to HTML folder
      unarchive:
        src: /tmp/healet.zip
        dest: /var/www/html/
        connection: local